### ISSUE TITLE
Not loading at all

### ISSUE THREAD

**Issue by christophwille** [Cecildt/angular2-O365-desktop-app#32]
I followed the steps outlined in the readme - on "npm run electron" the frame loads, but nothing else.

I got the following warnings on npm install:

λ npm install
npm WARN angular2@2.0.0-beta.17 requires a peer of reflect-metadata@0.1.2 but none was installed.
npm WARN angular2@2.0.0-beta.17 requires a peer of rxjs@5.0.0-beta.6 but none was installed.

But also on the TypeScript pass:

λ npm install -g typescript
`-- typescript@1.8.10

D:\Demos\e\o365  (angular2-o365-desktop-app@1.0.0)
λ npm run tsc

> angular2-o365-desktop-app@1.0.0 tsc D:\Demos\e\o365
> tsc -w

app/authHelper/authHelper.ts(1,16): error TS2304: Cannot find name 'require'.
app/authHelper/authHelper.ts(30,50): error TS2304: Cannot find name 'Promise'.
app/authHelper/authHelper.ts(31,21): error TS2304: Cannot find name 'Promise'.
app/authHelper/authHelper.ts(49,55): error TS2304: Cannot find name 'Promise'.
app/authHelper/authHelper.ts(50,21): error TS2304: Cannot find name 'Promise'.
app/authHelper/authHelper.ts(116,48): error TS2304: Cannot find name 'Promise'.
app/authHelper/authHelper.ts(117,21): error TS2304: Cannot find name 'Promise'.
app/authHelper/authHelper.ts(142,33): error TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature.
app/authHelper/authHelper.ts(189,33): error TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature.
app/login/login.ts(1,21): error TS2305: Module '"D:/Demos/e/o365/node_modules/angular2/core"' has no exported member 'View'.
node_modules/angular2/platform/browser.d.ts(78,90): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/application_ref.d.ts(38,88): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/application_ref.d.ts(92,42): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/application_ref.d.ts(151,33): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/change_detection/differs/default_keyvalue_differ.d.ts(23,15): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/change_detection/differs/default_keyvalue_differ.d.ts(25,16): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/di/reflective_provider.d.ts(103,123): error TS2304: Cannot find name 'Map'.

node_modules/angular2/src/core/di/reflective_provider.d.ts(103,165): error TS2304: Cannot find name 'Map'.

node_modules/angular2/src/core/linker/component_resolver.d.ts(8,53): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/linker/component_resolver.d.ts(12,44): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/linker/dynamic_component_loader.d.ts(59,148): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/linker/dynamic_component_loader.d.ts(100,144): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/linker/dynamic_component_loader.d.ts(105,139): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/linker/dynamic_component_loader.d.ts(106,135): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/async.d.ts(27,33): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/async.d.ts(28,45): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/collection.d.ts(1,25): error TS2304: Cannot find name 'MapConstructor'.
node_modules/angular2/src/facade/collection.d.ts(2,25): error TS2304: Cannot find name 'SetConstructor'.
node_modules/angular2/src/facade/collection.d.ts(4,27): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(4,39): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(7,9): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(8,30): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(11,43): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(12,27): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(14,23): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(15,25): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(100,41): error TS2304: Cannot find name 'Set'.
node_modules/angular2/src/facade/collection.d.ts(101,22): error TS2304: Cannot find name 'Set'.
node_modules/angular2/src/facade/collection.d.ts(102,25): error TS2304: Cannot find name 'Set'.
node_modules/angular2/src/facade/lang.d.ts(4,17): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/lang.d.ts(5,17): error TS2304: Cannot find name 'Set'.
node_modules/angular2/src/facade/lang.d.ts(71,59): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/promise.d.ts(2,14): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(8,32): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(9,38): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(10,35): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(10,93): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(11,34): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(11,50): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(12,32): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(12,149): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(13,43): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/http/headers.d.ts(43,59): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/http/url_search_params.d.ts(11,16): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/platform/browser/browser_adapter.d.ts(75,33): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/platform/dom/dom_adapter.d.ts(85,42): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/router/directives/router_outlet.d.ts(27,54): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/directives/router_outlet.d.ts(33,51): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/directives/router_outlet.d.ts(38,56): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/directives/router_outlet.d.ts(47,65): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/directives/router_outlet.d.ts(58,60): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/instruction.d.ts(124,34): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/instruction.d.ts(148,25): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/instruction.d.ts(164,34): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/instruction.d.ts(167,25): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/interfaces.d.ts(21,107): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/interfaces.d.ts(39,104): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/interfaces.d.ts(57,109): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/interfaces.d.ts(80,109): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/interfaces.d.ts(102,114): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/lifecycle/lifecycle_annotations.d.ts(29,100): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/route_config/route_config_impl.d.ts(101,19): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/route_definition.d.ts(20,20): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/route_definition.d.ts(35,20): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/route_registry.d.ts(52,66): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/router.d.ts(56,50): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/router.d.ts(68,46): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/router.d.ts(86,45): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/router.d.ts(99,34): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/router.d.ts(107,64): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/router.d.ts(112,85): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/router.d.ts(120,70): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/router.d.ts(128,43): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/router.d.ts(132,29): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/router.d.ts(138,19): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/router.d.ts(146,70): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(10,66): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(66,60): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(66,70): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/observable/PromiseObservable.d.ts(40,31): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/observable/PromiseObservable.d.ts(41,26): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/operator/toPromise.d.ts(7,59): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/operator/toPromise.d.ts(7,69): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/operator/toPromise.d.ts(9,9): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/operator/toPromise.d.ts(10,26): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/operator/toPromise.d.ts(10,36): error TS2304: Cannot find name 'Promise'.
app/assets/github-electron.d.ts(23,35): error TS2304: Cannot find name 'Buffer'.
app/assets/github-electron.d.ts(31,12): error TS2304: Cannot find name 'Buffer'.
app/assets/github-electron.d.ts(35,28): error TS2304: Cannot find name 'Buffer'.
app/assets/github-electron.d.ts(65,26): error TS2503: Cannot find namespace 'NodeJS'.
app/assets/github-electron.d.ts(103,33): error TS2503: Cannot find namespace 'NodeJS'.
app/assets/github-electron.d.ts(376,37): error TS2304: Cannot find name 'Buffer'.
app/assets/github-electron.d.ts(517,31): error TS2503: Cannot find namespace 'NodeJS'.
app/assets/github-electron.d.ts(719,34): error TS2304: Cannot find name 'Buffer'.
app/assets/github-electron.d.ts(925,23): error TS2503: Cannot find namespace 'NodeJS'.
app/assets/github-electron.d.ts(1117,31): error TS2503: Cannot find namespace 'NodeJS'.
app/assets/github-electron.d.ts(1227,24): error TS2503: Cannot find namespace 'NodeJS'.
app/assets/github-electron.d.ts(1421,38): error TS2503: Cannot find namespace 'NodeJS'.
app/assets/github-electron.d.ts(1682,11): error TS2304: Cannot find name 'Buffer'.
app/assets/github-electron.d.ts(1713,12): error TS2503: Cannot find namespace 'NodeJS'.
app/assets/github-electron.d.ts(1716,17): error TS2503: Cannot find namespace 'NodeJS'.
app/assets/github-electron.d.ts(1743,2): error TS2382: Specialized overload signature is not assignable to any non-specialized signature.
app/boot/boot.ts(3,28): error TS2305: Module '"D:/Demos/e/o365/node_modules/angular2/router"' has no exported member 'APP_BASE_HREF'.
10:47:45 AM - Compilation complete. Watching for file changes.

**Comment by Cecildt** [comment]
The application is currently broken. I will fix it in the next couple of days. Apologies.

**Comment by christophwille** [comment]
Thanks for the update

**Comment by christophwille** [comment]
Should I give it a try again or is it too early?

**Comment by Cecildt** [comment]
I fixed the upgrade to the latest release of Angular 2 RC. You should be
able now to startup the application and see the top menu bar.

I currently have an issue between webpack and electron latest release to
get authentication to work. Currently working with the webpack community to
solve the issue.

Trying my best to fix authentication this week.

**Comment by christophwille** [comment]
Can confirm that the build & startup work now (tested on a Mac) up to the login button.

**Comment by Cecildt** [comment]
I fixed the authentication part. The app should work fine now. Going forward I will keep the master branch stable and keep latest changes on a separate development branch. Going to have more structured releases to master branch.
