### ISSUE TITLE
Problems building latest master 062cc56

### ISSUE THREAD

**Issue by christophwille** [Cecildt/angular2-O365-desktop-app#52]
on running "npm run watch":

ERROR in ./src/authHelper/authHelper.ts
(3,29): error TS2307: Cannot find module '../adal/adal-config'.

on running "npm run tsc":

> angular2-o365-desktop-app@1.0.0 tsc D:\Demos\e\o365
> tsc

src/authHelper/authHelper.ts(3,29): error TS2307: Cannot find module '../adal/adal-config'.

So the same error - however, a .js file is available in /src/adal/. Typo in authHelper.ts?

**Comment by Cecildt** [comment]
That is due to the typescript compiler strict warning settings. It does not actually break the application. You could just rename the adal-config.js to adal-config.ts. Then you should not see the error message. I will fix this soon. Thanks for logging this. Much appreciated.

**Comment by Cecildt** [comment]
Problems solved. You should now have a clean build with webpack. "npm run watch"
